Fix Bluetooth failure due to invalid write len
projectceladon/libbt-vendor-intel pull request #14
Opened 2023-03-30 11:38 UTC by bpanda24

Correct length will be provided for writing mgmt command.

Tracked-On: OAM-107366

2023-04-03 06:27 UTC, balajim001 approved these changes
LGTM

2023-04-03 18:40 UTC, JeevakaPrabu requested changes
[Yesterday 9:43 PM] Badrappan, Jeevaka




- Introduce space before and after - ?
- Commit message format

Short summary
<blank line>
<Issue detailed>
<blank line>
<root cause detailed>
<blank line>
<Fix detailed>
<blank line>
Tracked-On:
Signed-off-by:

2023-04-03 18:40 UTC, JeevakaPrabu commented on bt_vendor.cc
> +  wrote = write(fd, &ev, sizeof(mgmt_pkt)-MGMT_EV_SIZE_MAX);
- Introduce space before and after - ?

2023-04-04 04:50 UTC, JeevakaPrabu approved these changes

2023-04-04 11:16 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5043

Done by "Panda, Bharat B" <bharat.b.panda@intel.com>

2023-04-04 11:41 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2904

Done by "Panda, Bharat B" <bharat.b.panda@intel.com>

2023-04-04 18:31 UTC, merged

2023-04-04 18:33 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3300